name: docker-publish

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  publish-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v3

      - name: Fetch source repository
        run: |
          git clone https://github.com/EnderWolf006/XBT.git source-repo
          cd source-repo
          git fetch origin

      - name: Compare branches
        id: compare
        run: |
          cd source-repo
          SOURCE_HASH=$(git rev-parse origin/main)
          TARGET_HASH=$(git rev-parse HEAD)
          if [ "$SOURCE_HASH" != "$TARGET_HASH" ]; then
            echo "source_hash=$SOURCE_HASH" >> $GITHUB_OUTPUT
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          else
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          fi

      - name: Get current date
        id: date
        run: |
          CURRENT_DATE=$(date +'%Y%m%d')
          echo "current_date=$CURRENT_DATE" >> $GITHUB_OUTPUT

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Run buildx and push
        if: steps.compare.outputs.changes_detected == 'true'
        env:
          DOCKER_REPO: www12x2/xbt-server-docker
          GITHUB_REPO: EnderWolf006/XBT
        run: |
          TAG=${{ steps.date.outputs.current_date }}-${{ steps.compare.outputs.source_hash }}
          docker buildx build \
            --output "type=image,push=true" \
            --platform linux/amd64,linux/arm64 \
            --tag ${DOCKER_REPO}:$TAG \
            --tag ${DOCKER_REPO}:latest \
            --file ./Dockerfile \
            .

      - name: Docker Hub logout
        if: always()
        run: docker logout
